<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.1.4</Version>
    <PackageId>Velonaceps.$(AssemblyName)</PackageId>
    <Title>KenobiMp3Parser</Title>
    <Authors>VelonacepsCalyxEggs</Authors>
    <Description>A lightweight MP3 metadata parser library, that create a hash of the audio stream data during metadata extraction.</Description>
    <Copyright>MIT</Copyright>
    <PackageProjectUrl>https://github.com/VelonacepsCalyxEggs/KenobiMP3Parser</PackageProjectUrl>
    <PackageReadmeFile>README.MD</PackageReadmeFile>
    <RepositoryUrl>https://github.com/VelonacepsCalyxEggs/KenobiMP3Parser</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>MP3,Parser,Hashing</PackageTags>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>9999</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>9999</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.MD">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" Version="10.0.10" />
  </ItemGroup>

</Project>
